cookies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('milk.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

milk/urls.py
from django.urls import path, re_path
from .views import *

app_name = "milk"

urlpatterns = [
    path('', landing, name="landing"),
    re_path(r'^signup/$', signup_view, name = "signup"),
    path('accounts/profile/', profile, name="profile")
]

milk/models.py
from django.db import models

# Create your models here.

milk/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import user_logged_in
# Create your views here.
def landing(request):
    return render(request, "cookies.html")

def signup_view(request):
    if request.method == 'POST':
        signupForm = UserCreationForm(request.POST)
        if signupForm.is_valid():
            signupForm.save()
        return render(request, "cookies.html")
    else:
        signupForm = UserCreationForm()
    return render(request, 'signup.html', {'form': signupForm})


def profile(request):
    return render(request, 'registration/profile.html')

milk/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <!--Import stylesheet for icons-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Milks and Cookies</title>
  </head>

  <body>
      {% block content %} {% endblock %}
  
  <!--JavaScript at end of body for optimized loading-->
  <script src="http://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/materialize.min.js'%}"></script>
  </body>
</html>

milk/templates/cookies.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 style="text-align: center;"> Welcome to this website!</h1>
    <h3 style="text-align: center;">If you want some cookies, please log in. If you don't have an account, you are welcomed to signup with us!</h3>
    <a id="signup-button" href="{% url 'milk:signup' %}" style="margin:auto; display: block; max-width: 15%; font-size: 18pt;" class="btn waves-effect"> Sign Up</a>
    <a id="login-button" href="{% url 'login' %}" style="margin:auto; margin-top:10px; display: block; max-width: 15%; font-size: 18pt;" class="btn waves-orange">Login</a>
    <img src="https://media.giphy.com/media/Cmr1OMJ2FN0B2/giphy.gif" style="margin:auto; margin-top:10px; display: block;" alt="">
</div>
{% endblock %}

milk/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form class="site-form" method="post">
    {% csrf_token %}
    {{form}}
    <button id="signup-button" type = "submit" class = "btn waves-effect waves-light">Sign Up</button>
    </form>
</div>

{% endblock %}